from altair import themes


AVAILABLE_THEMES = themes.names()

DEFAULT_COLOR_SCHEME = "category10"
DEFAULT_FACET_COLUMNS = 2
DEFAULT_LEGEND_ORIENTATION = "right"


DEFAULT_CHART_HEIGHT = 600
DEFAULT_CHART_WIDTH = 800
